version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    networks:
      - banking-net
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=banking_app
      - MYSQL_USER=bankingappuser
      - MYSQL_PASSWORD=bankingapppassword
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ../
    restart: on-failure
    networks:
      - banking-net
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/banking_app?useSSL=false",
        "spring.datasource.username" : "bankingappuser",
        "spring.datasource.password" : "bankingapppassword",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

networks:
  banking-net:
  
volumes:
  db: