apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  mysql-server: banking-app-mysql    # The name of mysql service
  mysql-database-name: bankingDb     # The name of the database used by the banking app
  mysql-user-username: bankingAppUser     # A new created user for the banking app